name: GameCI Unity

on:
  push:
  pull_request:

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # Speed up runs by caching the Unity Library folder
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Run Unity tests (editmode + playmode by default)
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL:   ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # projectPath: .   # uncomment and set if your project is in a subfolder

      # Build the project
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL:   ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD:${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL   # change to StandaloneWindows64, StandaloneOSX, Android, iOS, etc.
          # projectPath: .        # set if your project lives in a subfolder
          # unityVersion: auto    # default is auto; it reads ProjectSettings/ProjectVersion.txt

      # Upload the build as an artifact
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
